# apps/backend/pyproject.toml
[tool.ruff]
select = ["E", "F", "B", "I", "C", "D"] # Beispiel-Set: Errors, Flake8, Bugbear, isort, Complexity, Docstrings
ignore = ["E501"] # Beispiel: Ignoriere "Line too long"
line-length = 120 # Beispiel: Erhöhe die maximale Zeilenlänge

exclude = [
    ".git",
    "__pycache__",
    "venv",
    "migrations", # Django migrations
    "node_modules",
]

[tool.ruff.lint]
# Spezifische Einstellungen für den Linter

[tool.ruff.format]
# Spezifische Einstellungen für den Formatter