repos:
  # Allgemeine Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  # Python Hooks (f端r Django Backend mit Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5 # Aktuelle Version pr端fen
    hooks:
      - id: ruff
        args: ["apps/backend/"]
        language_version: python3.13 # Wichtig!
      - id: ruff-format
        args: ["apps/backend/"]
        language_version: python3.13 # Wichtig!

  # Node.js Hooks (f端r React Frontend)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, css, markdown, yaml, json, ts, tsx]
        args: ["--ignore-path", "apps/frontend/.prettierignore"] # Stellt sicher, dass diese Datei im Frontend-Ordner existiert
        files: ^apps/frontend/ # F端ge diese Zeile hinzu, um explizit nur Frontend-Dateien zu bearbeiten

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: ^apps/frontend/.*\.(js|jsx|ts|tsx)$
        args: ["--config", "apps/frontend/.eslintrc.js", "--ignore-path", "apps/frontend/.eslintignore"] # Stellt sicher, dass diese Dateien im Frontend-Ordner existieren
        language: system
        pass_filenames: false

  # Conventional Commits Linter (Commitlint)
  - repo: local
    hooks:
      - id: commitlint
        name: Commitlint
        entry: npx --no-install commitlint --edit ${1}
        language: system
        types: [commit-msg]