# Generated by Django 5.2.1 on 2025-05-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('human_readable_name', models.CharField(blank=True, help_text='Optional: Human-readable name for display', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('full_stack', 'Full Stack'), ('devops', 'DevOps'), ('designer', 'Designer'), ('pm', 'Project Manager'), ('other', 'Other')], default='full_stack', help_text='Project role', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('work', 'Work'), ('private', 'Private'), ('study', 'Study'), ('other', 'Other')], default='private', max_length=20),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in the project', related_name='projects', to='portfolio.technology'),
        ),
    ]
