# Generated by Django 5.2.1 on 2025-05-29 09:58
import logging
import django.utils.timezone
from django.db import migrations, models

logger = logging.getLogger(__name__)

def add_technoligies(apps, schema_editor):
    Technology = apps.get_model('portfolio', 'Technology')
    technologies = [
        {"name": "python", "human_readable_name": "Python", "description": "A versatile programming language."},
        {"name": "django", "human_readable_name": "Django", "description": "A high-level Python web framework."},
        {"name": "javascript", "human_readable_name": "JavaScript", "description": "A programming language for web development."},
        {"name": "react", "human_readable_name": "React", "description": "A JavaScript library for building user interfaces."},
        {"name": "docker", "human_readable_name": "Docker", "description": "A platform for developing, shipping, and running applications in containers."},
        {"name": "typescript", "human_readable_name": "TypeScript", "description": "A typed superset of JavaScript that compiles to plain JavaScript."},
        {"name": "kubernetes", "human_readable_name": "Kubernetes", "description": "An open-source system for automating deployment, scaling, and management of containerized applications."},
        {"name": "graphql", "human_readable_name": "GraphQL", "description": "A query language for APIs and a runtime for executing those queries with your existing data."},
        {"name": "postgresql", "human_readable_name": "PostgreSQL", "description": "A powerful, open source object-relational database system."},
        {"name": "mysql", "human_readable_name": "MySQL", "description": "An open-source relational database management system."},
        {"name": "redis", "human_readable_name": "Redis", "description": "An in-memory data structure store, used as a database, cache, and message broker."},
        {"name": "nginx", "human_readable_name": "Nginx", "description": "A high-performance HTTP server and reverse proxy."},
        {"name": "aws", "human_readable_name": "Amazon Web Services (AWS)", "description": "A comprehensive cloud computing platform provided by Amazon."},
        {"name": "azure", "human_readable_name": "Microsoft Azure", "description": "A cloud computing service created by Microsoft for building, testing, deploying, and managing applications through Microsoft-managed data centers."},
        {"name": "git", "human_readable_name": "Git", "description": "A distributed version control system for tracking changes in source code during software development."},
        {"name": "html", "human_readable_name": "HTML", "description": "The standard markup language for documents designed to be displayed in a web browser."},
        {"name": "css", "human_readable_name": "CSS", "description": "A style sheet language used for describing the presentation of a document written in HTML or XML."},
        {"name": "flutter", "human_readable_name": "Flutter", "description": "An open-source UI software development toolkit created by Google for building natively compiled applications for mobile, web, and desktop from a single codebase."},
        {"name": "swift", "human_readable_name": "Swift", "description": "A powerful and intuitive programming language for iOS, macOS, watchOS, and tvOS app development."},
        {"name": "kotlin", "human_readable_name": "Kotlin", "description": "A modern programming language that makes developers happier, used for Android development."},
        {"name": "flutter", "human_readable_name": "Flutter", "description": "A UI toolkit for building natively compiled applications for mobile, web, and desktop from a single codebase."},
        {"name": "vuejs", "human_readable_name": "Vue.js", "description": "A progressive JavaScript framework for building user interfaces."},
        {"name": "tailwindcss", "human_readable_name": "Tailwind CSS", "description": "A utility-first CSS framework for creating custom designs without leaving your HTML."},
        {"name": "nextjs", "human_readable_name": "Next.js", "description": "A React framework for production with server-side rendering and static site generation."},
        {"name": "flask", "human_readable_name": "Flask", "description": "A lightweight WSGI web application framework in Python."},
        {"name": "springboot", "human_readable_name": "Spring Boot", "description": "An extension of the Spring framework that simplifies the setup and development of new applications."},
        {"name": "laravel", "human_readable_name": "Laravel", "description": "A PHP framework for web artisans, providing an elegant syntax and powerful features."},
        {"name": "csharp", "human_readable_name": "C#", "description": "A modern, object-oriented programming language developed by Microsoft."},
        {"name": "ruby", "human_readable_name": "Ruby", "description": "A dynamic, open source programming language with a focus on simplicity and productivity."},
        {"name": "golang", "human_readable_name": "Go", "description": "An open-source programming language designed for simplicity and efficiency."},
        {"name": "rust", "human_readable_name": "Rust", "description": "A systems programming language focused on safety and performance."},
        {"name": "flutter", "human_readable_name": "Flutter", "description": "A UI toolkit for building natively compiled applications for mobile, web, and desktop from a single codebase."},
        {"name": "tensorflow", "human_readable_name": "TensorFlow", "description": "An end-to-end open source platform for machine learning."},
        {"name": "pytorch", "human_readable_name": "PyTorch", "description": "An open source machine learning library based on the Torch library."},
        {"name": "scikit-learn", "human_readable_name": "Scikit-learn", "description": "A machine learning library for Python that features various classification, regression, and clustering algorithms."},
        {"name": "opencv", "human_readable_name": "OpenCV", "description": "An open source computer vision and machine learning software library."},
        {"name": "apache_spark", "human_readable_name": "Apache Spark", "description": "An open-source unified analytics engine for large-scale data processing."},
        {"name": "elasticsearch", "human_readable_name": "Elasticsearch", "description": "A distributed, RESTful search and analytics engine capable of addressing a growing number of use cases."},
        {"name": "grafana", "human_readable_name": "Grafana", "description": "An open-source platform for monitoring and observability."},
        {"name": "prometheus", "human_readable_name": "Prometheus", "description": "An open-source systems monitoring and alerting toolkit originally built at SoundCloud."},
        {"name": "ansible", "human_readable_name": "Ansible", "description": "An open-source automation tool for software provisioning, configuration management, and application deployment."},
        {"name": "terraform", "human_readable_name": "Terraform", "description": "An open-source infrastructure as code software tool created by HashiCorp."},
        {"name": "jenkins", "human_readable_name": "Jenkins", "description": "An open-source automation server for continuous integration and continuous delivery."},
        {"name": "circleci", "human_readable_name": "CircleCI", "description": "A continuous integration and continuous delivery platform that automates development workflows."},
        {"name": "gitlab_ci", "human_readable_name": "GitLab CI/CD", "description": "A built-in continuous integration and deployment tool in GitLab."},
        {"name": "apache_kafka", "human_readable_name": "Apache Kafka", "description": "A distributed event streaming platform capable of handling trillions of events a day."},
        {"name": "rabbitmq", "human_readable_name": "RabbitMQ", "description": "An open-source message broker software that originally implemented the Advanced Message Queuing Protocol (AMQP)."},
        {"name": "apache_cassandra", "human_readable_name": "Apache Cassandra", "description": "A free and open-source distributed NoSQL database management system designed to handle large amounts of data across many commodity servers."},
        {"name": "mongodb", "human_readable_name": "MongoDB", "description": "A source-available cross-platform document-oriented database program."},
        {"name": "clickhouse", "human_readable_name": "ClickHouse", "description": "A columnar database management system for online analytical processing (OLAP)."},
        {"name": "redis", "human_readable_name": "Redis", "description": "An open-source, in-memory data structure store, used as a database, cache, and message broker."},
        {"name": "apache_hadoop", "human_readable_name": "Apache Hadoop", "description": "An open-source software framework for storing and processing large datasets."},
        {"name": "apache_airflow", "human_readable_name": "Apache Airflow", "description": "A platform to programmatically author, schedule, and monitor workflows."},
        {"name": "fastapi", "human_readable_name": "FastAPI", "description": "A modern, fast (high-performance), web framework for building APIs with Python 3.6+ based on standard Python type hints."},
        {"name": "svelte", "human_readable_name": "Svelte", "description": "A modern JavaScript framework for building user interfaces."},
        {"name": "nuxtjs", "human_readable_name": "Nuxt.js", "description": "A framework for creating Vue.js applications with server-side rendering capabilities."},
        {"name": "ionic", "human_readable_name": "Ionic", "description": "A complete open-source SDK for hybrid mobile app development."},
        {"name": "flutter_web", "human_readable_name": "Flutter Web", "description": "A web implementation of the Flutter framework for building web applications."},
        {"name": "electron", "human_readable_name": "Electron", "description": "A framework for building cross-platform desktop applications using web technologies."},
        {"name": "blazor", "human_readable_name": "Blazor", "description": "A framework for building interactive web applications using C# instead of JavaScript."},
        {"name": "vuex", "human_readable_name": "Vuex", "description": "A state management pattern + library for Vue.js applications."},
        {"name": "redux", "human_readable_name": "Redux", "description": "A predictable state container for JavaScript apps."},
        {"name": "mobx", "human_readable_name": "MobX", "description": "A simple, scalable state management solution for JavaScript applications."},
        {"name": "styled_components", "human_readable_name": "Styled Components", "description": "A library for React and React Native that allows you to use component-level styles in your application."},
        {"name": "material_ui", "human_readable_name": "Material-UI", "description": "A popular React UI framework that implements Google's Material Design."},
        {"name": "ant_design", "human_readable_name": "Ant Design", "description": "A design system with a set of high-quality React components out of the box."},
        {"name": "bootstrap", "human_readable_name": "Bootstrap", "description": "The most popular HTML, CSS, and JS library in the world for responsive, mobile-first projects on the web."},
        {"name": "bulma", "human_readable_name": "Bulma", "description": "A modern CSS framework based on Flexbox."},
        {"name": "foundation", "human_readable_name": "Foundation", "description": "A responsive front-end framework similar to Bootstrap."},
        {"name": "d3js", "human_readable_name": "D3.js", "description": "A JavaScript library for producing dynamic, interactive data visualizations in web browsers."},
        {"name": "threejs", "human_readable_name": "Three.js", "description": 'A cross-browser JavaScript library and application programming interface used to create and display animated 3D computer graphics in a web browser.'},
        {"name": "socketio", "human_readable_name": "Socket.IO", "description": "A JavaScript library for real-time web applications, enabling real-time, bidirectional and event-based communication."},
        {"name": "websockets", "human_readable_name": "WebSockets", "description": "A protocol providing full-duplex communication channels over a single TCP connection."},
        {"name": "graphql_subscriptions", "human_readable_name": "GraphQL Subscriptions", "description": "A way to push updates to clients in real-time using GraphQL."},
        {"name": "oauth2", "human_readable_name": "OAuth 2.0", "description": "An open standard for access delegation commonly used for token-based authentication and authorization."},
        {"name": "jwt", "human_readable_name": "JSON Web Tokens (JWT)", "description": "A compact, URL-safe means of representing claims to be transferred between two parties."},
        {"name": "openid_connect", "human_readable_name": "OpenID Connect", "description": "An authentication layer on top of OAuth 2.0 that allows clients to verify the identity of an end-user based on the authentication performed by an authorization server."},
        {"name": "saml", "human_readable_name": "SAML (Security Assertion Markup Language)", "description": 'An open standard for exchanging authentication and authorization data between parties, particularly between an identity provider and a service provider.'},
        {"name": "apache_httpd", "human_readable_name": "Apache HTTP Server", "description": 'A free and open-source cross-platform web server software.'},
        {"name": "nginx_ingress_controller", "human_readable_name": 'Nginx Ingress Controller', 'description': 'An Nginx-based ingress controller for Kubernetes.'},
        {"name": 'haproxy', 'human_readable_name': 'HAProxy', 'description': 'A free, open-source software that provides a high availability load balancer and proxy server for TCP and HTTP-based applications.'},
        {"name": "caddy", "human_readable_name": "Caddy", "description": "A modern web server with automatic HTTPS."},
        {"name": "apache_maven", "human_readable_name": "Apache Maven", "description": "A build automation tool used primarily for Java projects."},
        {"name": "gradle", "human_readable_name": "Gradle", "description": "An open-source build automation tool that is designed to be flexible enough to build almost any type of software."},
        {"name": "ant", "human_readable_name": "Apache Ant", "description": "A Java library and command-line tool used for automating software build processes."},
        {"name": "makefile", "human_readable_name": "Makefile", "description": 'A file containing a set of directives used with the make build automation tool.'},
        {"name": "cmake", "human_readable_name": 'CMake', 'description': 'A cross-platform free and open-source software tool for managing the build process of software using a compiler-independent method.'},
        {"name": 'bazel', 'human_readable_name': 'Bazel', 'description': 'A build and test tool that supports multiple languages and platforms.'},
        {"name": 'vagrant', 'human_readable_name': 'Vagrant', 'description': 'An open-source tool for building and maintaining portable virtual software development environments.'},
        {"name": 'kafka_streams', 'human_readable_name': 'Kafka Streams', 'description': 'A client library for building applications and microservices, where the input and output data are stored in Kafka clusters.'},
        {"name": 'apache_flume', 'human_readable_name': 'Apache Flume', 'description': 'A distributed, reliable, and available service for efficiently collecting, aggregating, and moving large amounts of log data.'},
        {"name": 'apache_spark_streaming', 'human_readable_name': 'Apache Spark Streaming', 'description': 'An extension of the core Spark API that enables scalable, high-throughput, fault-tolerant stream processing of live data streams.'},
        {"name": 'apache_kafka_connect', 'human_readable_name': 'Apache Kafka Connect', 'description': 'A tool for scalably and reliably streaming data between Apache Kafka and other systems.'},
        {"name": 'apache_kafka_streams', 'human_readable_name': 'Apache Kafka Streams', 'description': 'A client library for building applications and microservices, where the input and output data are stored in Kafka clusters.'},
        {"name": 'apache_spark_sql', 'human_readable_name': 'Apache Spark SQL', 'description': 'A module in Apache Spark for structured data processing.'},
        {"name": 'apache_spark_ml', 'human_readable_name': 'Apache Spark MLlib', 'description': 'A scalable machine learning library in Apache Spark.'},
        {"name": 'apache_spark_graphx', 'human_readable_name': 'Apache Spark GraphX', 'description': "A component of Apache Spark for graphs and graph-parallel computation."},
        {"name": "apache_spark_rdd", "human_readable_name": "Apache Spark RDD", "description": "Resilient Distributed Dataset, a fundamental data structure of Apache Spark."},
        {"name": "apache_spark_dataframe", "human_readable_name": "Apache Spark DataFrame", "description": "A distributed collection of data organized into named columns."},
        {"name": "apache_spark_dataset", "human_readable_name": "Apache Spark Dataset", "description": "A distributed collection of data that provides the benefits of both RDDs and DataFrames."},
        {"name": "apache_spark_streaming", "human_readable_name": "Apache Spark Streaming", "description": "An extension of the core Spark API that enables scalable, high-throughput, fault-tolerant stream processing of live data streams."},
        {"name": "apache_spark_graphframes", "human_readable_name": "Apache Spark GraphFrames", "description": "A package for Apache Spark that provides DataFrame-based graphs."},
        {"name": "apache_spark_mllib", "human_readable_name": "Apache Spark MLlib", "description": "A scalable machine learning library in Apache Spark."},
        {"name": "apache_spark_ml_pipeline", "human_readable_name": "Apache Spark ML Pipeline", "description": "A tool for building machine learning pipelines in Apache Spark."},
        {"name": "apache_spark_sql_query", "human_readable_name": "Apache Spark SQL Query", "description": "A module in Apache Spark for structured data processing."},
        {"name": "apache_spark_sql_dataframe", "human_readable_name": "Apache Spark SQL DataFrame", "description": "A distributed collection of data organized into named columns."},
        {"name": 'apache_spark_sql_dataset', 'human_readable_name': 'Apache Spark SQL Dataset', 'description': 'A distributed collection of data that provides the benefits of both RDDs and DataFrames.'},
        {"name": 'apache_spark_sql_rdd', 'human_readable_name': 'Apache Spark SQL RDD', 'description': 'Resilient Distributed Dataset, a fundamental data structure of Apache Spark.'},
        {"name": 'apache_spark_sql_graphx', 'human_readable_name': 'Apache Spark SQL GraphX', 'description': 'A component of Apache Spark for graphs and graph-parallel computation.'},
        {"name": 'apache_spark_sql_mllib', 'human_readable_name': 'Apache Spark SQL MLlib', 'description': 'A scalable machine learning library in Apache Spark.'},
        {"name": 'apache_spark_sql_streaming', 'human_readable_name': 'Apache Spark SQL Streaming', 'description': 'An extension of the core Spark API that enables scalable, high-throughput, fault-tolerant stream processing of live data streams.'},
        {"name": 'apache_spark_sql_graphframes', 'human_readable_name': 'Apache Spark SQL GraphFrames', 'description': 'A package for Apache Spark that provides DataFrame-based graphs.'},
        {"name": 'apache_spark_sql_mllib_pipeline', 'human_readable_name': 'Apache Spark SQL MLlib Pipeline', 'description': 'A tool for building machine learning pipelines in Apache Spark.'},
        {"name": 'apache_spark_sql_streaming_pipeline', 'human_readable_name': 'Apache Spark SQL Streaming Pipeline', 'description': 'A tool for building streaming pipelines in Apache Spark.'},
        {"name": 'apache_spark_sql_graphx_pipeline', 'human_readable_name': 'Apache Spark SQL GraphX Pipeline', 'description': 'A component of Apache Spark for graphs and graph-parallel computation.'},
        {"name": "apache_spark_sql_graphframes_pipeline", "human_readable_name": "Apache Spark SQL GraphFrames Pipeline", "description": "A package for Apache Spark that provides DataFrame-based graphs."},
    ]

    seen_names = set()
    for tech in technologies:
        if tech["name"] in seen_names:
            continue
        seen_names.add(tech["name"])
        logger.info(f"Adding technology: {tech['human_readable_name']}")
        Technology.objects.get_or_create(**tech)

def remove_technologies(apps, schema_editor):
    Technology = apps.get_model('portfolio', 'Technology')
    Technology.objects.all().delete()
    logger.info("All technologies have been removed.")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technology_project_end_date_project_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(add_technoligies, remove_technologies),
    ]
