# Generated by Django 5.2.1 on 2025-12-26 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_technology_created_at_technology_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='related_project',
            field=models.ForeignKey(blank=True, default=None, help_text='Related project', null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
    ]
