# Generated by Django 5.2.1 on 2025-12-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_load_initial_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='related_project',
            field=models.ForeignKey(blank=True, default=None, help_text='Related project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.project'),
        ),
    ]
